Traceback (most recent call last):
  File "/users/boeiradi/COLD_project/postprocessing/waom_notebook/Floats/grid_points_to_spherical.py", line 97, in <module>
    long,lat = grid_to_spherical(x,y,dg)
  File "/users/boeiradi/COLD_project/postprocessing/waom_notebook/Floats/grid_points_to_spherical.py", line 85, in grid_to_spherical
    x_i,y_i = interpolate(x[i],y[i],ds)
  File "/users/boeiradi/COLD_project/postprocessing/waom_notebook/Floats/grid_points_to_spherical.py", line 50, in interpolate
    interp_arr = interpn((x_shape, y_shape), lat_values, interp_points)
  File "/scratch/project_2000339/boeiradi/anaconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 2699, in interpn
    "in dimension %d" % i)
ValueError: One of the requested xi is out of bounds in dimension 0
srun: error: r08m03: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=12031934.0
